name: Publish NuGet Package
description: Builds project and publishes to NuGet
inputs:
  project:
    description: The path to the .csproj file
    required: true
  nuget-key:
    description: The NuGet API key
    required: true
runs:
  using: composite
  steps:
    - name: Build
      run: dotnet build -c Release ${{ inputs.project }}
      shell: bash
    - name: Pack
      run: dotnet pack --no-build -c Release ${{ inputs.project }} -o .
      shell: bash
    - name: Extract Version
      id: version
      run: |
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" version.props)
        echo "::set-output name=version::$version"
      shell: bash
    - name: Push
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ inputs.nuget-key }} --skip-duplicate -n --version "${{ steps.version.outputs.version }}"
      shell: bash
